### ISSUE TITLE
Error yii migrate

### ISSUE THREAD

**Issue by putrapuices** [piantgrunger/POS-stisla#1]
λ yii migrate
Yii Migration Tool (based on Yii v2.0.46-dev)

Creating migration history table "migration"...Done.
Total 27 new migrations to be applied:
        m130524_201442_init
        m170228_064223_rbac_create
        m170228_064635_mimin_init
        m190526_032131_jenis_barang
        m190526_033353_barang
        m190526_041426_gudang
        m190526_060518_supplier
        m190526_062809_customer
        m190526_064554_satuan
        m190526_071005_satuanbarang
        m190526_072452_itemsatuanbarang
        m190526_080444_pembelian
        m190526_090206_alterpembelian
        m190917_122110_alterpembelian
        m190917_143845_alterpembelian
        m200212_162311_alterpemb
        m200214_023058_penjualan
        m200214_072335_penjualan
        m200713_052835_alterBarang
        m200919_030524_penjualan
        m200919_063042_setting
        m200920_012835_alterSetting
        m200920_080019_alterBarang
        m210508_235530_alterSetting
        m210509_012225_vWstok
        m210509_014148_vWstok
        m210509_215027_vWstok

Apply the above migrations? (yes|no) [no]:yes
*** applying m130524_201442_init
    > create table {{%user}} ... done (time: 0.052s)
    > execute SQL: INSERT INTO `user` (`id`, `username`, `auth_key`, `password_hash`, `password_reset_token`, `email`, `status`, `created_at`, `updated_at`) VALUES (NULL, 'admin', 'Bj2xEpff-WmRLtY4TyHPHxRp6eAxsNZ0', '$2y$13$lyzLwLoeBeCxjFtGgQVPquL0qaL6F1ygdBgqTnKE22Q2x.dwAaQ9S', NULL, 'piant.grunger@gmail.com', '10', '1485769884', '1488270381') ... done (time: 0.003s)
*** applied m130524_201442_init (time: 0.064s)

*** applying m170228_064223_rbac_create
    > create table {{%auth_rule}} ... done (time: 0.053s)
    > create table {{%auth_item}} ... done (time: 0.040s)
    > create index idx-auth_item-type on {{%auth_item}} (type) ... done (time: 0.028s)
    > create table {{%auth_item_child}} ... done (time: 0.052s)
    > create table {{%auth_assignment}} ... done (time: 0.035s)
*** applied m170228_064223_rbac_create (time: 0.221s)

*** applying m170228_064635_mimin_init
    > create table {{%route}} ... done (time: 0.033s)
*** applied m170228_064635_mimin_init (time: 0.038s)

*** applying m190526_032131_jenis_barang
    > create table jenis_barang ... done (time: 0.043s)
*** applied m190526_032131_jenis_barang (time: 0.050s)

*** applying m190526_033353_barang
    > create table barang ... done (time: 0.034s)
    > add foreign key fk_barang_jenis: barang (id_jenis_barang) references jenis_barang (id) ... done (time: 0.071s)
*** applied m190526_033353_barang (time: 0.110s)

*** applying m190526_041426_gudang
    > create table gudang ... done (time: 0.032s)
*** applied m190526_041426_gudang (time: 0.037s)

*** applying m190526_060518_supplier
    > create table supplier ... done (time: 0.040s)
*** applied m190526_060518_supplier (time: 0.047s)

*** applying m190526_062809_customer
    > create table customer ... done (time: 0.050s)
*** applied m190526_062809_customer (time: 0.054s)

*** applying m190526_064554_satuan
    > create table satuan ... done (time: 0.025s)
*** applied m190526_064554_satuan (time: 0.029s)

*** applying m190526_071005_satuanbarang
    > add column id_satuan_std integer NOT NULL to table barang ... done (time: 0.054s)
    > add foreign key fk_barang_satuan: barang (id_satuan_std) references satuan (id) ... done (time: 0.052s)
*** applied m190526_071005_satuanbarang (time: 0.113s)

*** applying m190526_072452_itemsatuanbarang
    > create table item_satuan_barang ... done (time: 0.033s)
    > add foreign key fk_item_barang_satuan: item_satuan_barang (id_satuan) references satuan (id) ... done (time: 0.058s)
    > add foreign key fk_item_barang_satuan2: item_satuan_barang (id_barang) references barang (id) ... done (time: 0.100s)
*** applied m190526_072452_itemsatuanbarang (time: 0.197s)

*** applying m190526_080444_pembelian
    > create table pembelian ... done (time: 0.036s)
    > create table item_pembelian ... done (time: 0.052s)
    > add foreign key fk_pembelian_supp: pembelian (id_supplier) references supplier (id) ... done (time: 0.081s)
    > add foreign key fk_item_pembelian: item_pembelian (id_pembelian) references pembelian (id) ... done (time: 0.051s)
    > add foreign key fk_item_pembelian_brg: item_pembelian (id_barang) references barang (id) ... done (time: 0.056s)
    > add foreign key fk_item_pembelian_satuan: item_pembelian (id_satuan) references satuan (id) ... done (time: 0.055s)
*** applied m190526_080444_pembelian (time: 0.342s)

*** applying m190526_090206_alterpembelian
    > add column harga decimal(19,2) NOT NULL DEFAULT 0 to table item_pembelian ... done (time: 0.052s)
    > add column sub_total decimal(19,2) NOT NULL DEFAULT 0 to table item_pembelian ... done (time: 0.050s)
*** applied m190526_090206_alterpembelian (time: 0.108s)

*** applying m190917_122110_alterpembelian
    > add column id_gudang integer to table pembelian ... done (time: 0.052s)
*** applied m190917_122110_alterpembelian (time: 0.057s)

*** applying m190917_143845_alterpembelian
    > drop foreign key fk_item_pembelian from table item_pembelian ... done (time: 0.015s)
    > add foreign key fk_item_pembelian: item_pembelian (id_pembelian) references pembelian (id) ... done (time: 0.057s)
    > add column jenis_ppn string(10) to table pembelian ... done (time: 0.045s)
    > add column ppn decimal(19,2) to table pembelian ... done (time: 0.064s)
    > add column dpp decimal(19,2) to table pembelian ... done (time: 0.049s)
    > add column grand_total decimal(19,2) to table pembelian ... done (time: 0.044s)
*** applied m190917_143845_alterpembelian (time: 0.284s)

*** applying m200212_162311_alterpemb
    > drop column dpp from table pembelian ... done (time: 0.049s)
    > drop column grand_total from table pembelian ... done (time: 0.060s)
*** applied m200212_162311_alterpemb (time: 0.115s)

*** applying m200214_023058_penjualan
    > create table penjualan ... done (time: 0.036s)
    > create table item_penjualan ... done (time: 0.033s)
    > add foreign key fk_penjualan_cust: penjualan (id_customer) references customer (id) ... done (time: 0.054s)
    > add foreign key fk_penjualan_gudang: penjualan (id_gudang) references gudang (id) ... done (time: 0.048s)
    > add foreign key fk_item_penjualan: item_penjualan (id_penjualan) references penjualan (id) ... done (time: 0.056s)
    > add foreign key fk_item_penjualan_brg: item_penjualan (id_barang) references barang (id) ... done (time: 0.056s)
    > add foreign key fk_item_penjualan_satuan: item_penjualan (id_satuan) references satuan (id) ... done (time: 0.049s)
*** applied m200214_023058_penjualan (time: 0.346s)

*** applying m200214_072335_penjualan
    > drop foreign key fk_item_penjualan from table item_penjualan ... done (time: 0.016s)
    > add foreign key fk_item_penjualan: item_penjualan (id_penjualan) references penjualan (id) ... done (time: 0.059s)
*** applied m200214_072335_penjualan (time: 0.081s)

*** applying m200713_052835_alterBarang
    > add column harga_jual decimal(19,2) to table barang ... done (time: 0.043s)
*** applied m200713_052835_alterBarang (time: 0.048s)

*** applying m200919_030524_penjualan
    > add column total decimal(19,2) to table penjualan ... done (time: 0.048s)
    > add column bayar decimal(19,2) to table penjualan ... done (time: 0.038s)
    > add column kembali decimal(19,2) to table penjualan ... done (time: 0.045s)
*** applied m200919_030524_penjualan (time: 0.137s)

*** applying m200919_063042_setting
    > create table setting ... done (time: 0.036s)
*** applied m200919_063042_setting (time: 0.042s)

*** applying m200920_012835_alterSetting
    > add column no_dok_penjualan string(50) to table setting ... done (time: 0.064s)
*** applied m200920_012835_alterSetting (time: 0.070s)

*** applying m200920_080019_alterBarang
    > add column barcode string(100) to table barang ... done (time: 0.056s)
*** applied m200920_080019_alterBarang (time: 0.062s)

*** applying m210508_235530_alterSetting
    > add column no_dokumen string to table setting ... done (time: 0.039s)
*** applied m210508_235530_alterSetting (time: 0.044s)

*** applying m210509_012225_vWstok
    > execute SQL: CREATE VIEW stok as
        SELECT no_dokumen,tanggal,id_barang,id_satuan,b.kode AS kode_barang,b.nama AS nama_barang,d.qty AS masuk, 0 AS keluar,s.kode AS satuan

        FROM pembelian p
        INNER JOIN item_pembelian d ON p.id=d.id_pembelian
        INNER JOIN barang b ON d.id_barang =b.id
        INNER JOIN satuan s ON s.id = d.id_satuan
        UNION all

        SELECT no_dokumen,tanggal,id_barang,id_satuan,b.kode AS kode_barang,b.nama AS nama_barang,0 AS masuk, d.qty AS keluar,s.kode AS satuan

        FROM penjualan p
        INNER JOIN item_penjualan d ON p.id=d.id_penjualan
        INNER JOIN barang b ON d.id_barang =b.id
        INNER JOIN satuan s ON s.id = d.id_satuan ... done (time: 0.008s)
*** applied m210509_012225_vWstok (time: 0.021s)

*** applying m210509_014148_vWstok
    > execute SQL:
      ALTER VIEW stok as

SELECT *  , SUM(masuk-keluar) OVER(ORDER BY CONCAT(id_gudang,urutan,tanggal,no_dokumen)) AS saldo from (

SELECT '1' AS urutan,'Pembelian' as ref , no_dokumen,tanggal,id_gudang,id_barang,id_satuan,b.kode AS kode_barang,b.nama AS nama_barang,d.qty AS masuk, 0 AS keluar,s.kode AS satuan

FROM pembelian p
INNER JOIN item_pembelian d ON p.id=d.id_pembelian
INNER JOIN barang b ON d.id_barang =b.id
INNER JOIN satuan s ON s.id = d.id_satuan
INNER JOIN gudang g ON g.id =p.id_gudang

UNION all

SELECT '2' AS urutan, 'Penjualan' AS ref ,no_dokumen,tanggal,id_gudang,id_barang,id_satuan,b.kode AS kode_barang,b.nama AS nama_barang,0 AS masuk, d.qty AS keluar,s.kode AS satuan

FROM penjualan p
INNER JOIN item_penjualan d ON p.id=d.id_penjualan
INNER JOIN barang b ON d.id_barang =b.id
INNER JOIN satuan s ON s.id = d.id_satuan
INNER JOIN gudang g ON g.id =p.id_gudang

) d
ORDER BY id_gudang,urutan,tanggal,no_dokumen

       ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(ORDER BY CONCAT(id_gudang,urutan,tanggal,no_dokumen)) AS saldo from (

SELECT '' at line 3
The SQL being executed was:
      ALTER VIEW stok as

SELECT *  , SUM(masuk-keluar) OVER(ORDER BY CONCAT(id_gudang,urutan,tanggal,no_dokumen)) AS saldo from (

SELECT '1' AS urutan,'Pembelian' as ref , no_dokumen,tanggal,id_gudang,id_barang,id_satuan,b.kode AS kode_barang,b.nama AS nama_barang,d.qty AS masuk, 0 AS keluar,s.kode AS satuan

FROM pembelian p
INNER JOIN item_pembelian d ON p.id=d.id_pembelian
INNER JOIN barang b ON d.id_barang =b.id
INNER JOIN satuan s ON s.id = d.id_satuan
INNER JOIN gudang g ON g.id =p.id_gudang

UNION all

SELECT '2' AS urutan, 'Penjualan' AS ref ,no_dokumen,tanggal,id_gudang,id_barang,id_satuan,b.kode AS kode_barang,b.nama AS nama_barang,0 AS masuk, d.qty AS keluar,s.kode AS satuan

FROM penjualan p
INNER JOIN item_penjualan d ON p.id=d.id_penjualan
INNER JOIN barang b ON d.id_barang =b.id
INNER JOIN satuan s ON s.id = d.id_satuan
INNER JOIN gudang g ON g.id =p.id_gudang

) d
ORDER BY id_gudang,urutan,tanggal,no_dokumen

       (E:\laragon\www\posstisla\vendor\yiisoft\yii2\db\Schema.php:676)
#0 E:\laragon\www\posstisla\vendor\yiisoft\yii2\db\Command.php(1307): yii\db\Schema->convertException(Object(PDOException), '\n      ALTER VI...')
#1 E:\laragon\www\posstisla\vendor\yiisoft\yii2\db\Command.php(1102): yii\db\Command->internalExecute('\n      ALTER VI...')
#2 E:\laragon\www\posstisla\vendor\yiisoft\yii2\db\Migration.php(219): yii\db\Command->execute()
#3 E:\laragon\www\posstisla\migrations\m210509_014148_vWstok.php(15): yii\db\Migration->execute('\n      ALTER VI...')
#4 E:\laragon\www\posstisla\vendor\yiisoft\yii2\db\Migration.php(114): m210509_014148_vWstok->safeUp()
#5 E:\laragon\www\posstisla\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(758): yii\db\Migration->up()
#6 E:\laragon\www\posstisla\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(216): yii\console\controllers\BaseMigrateController->migrateUp('m210509_014148_...')
#7 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#8 E:\laragon\www\posstisla\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#9 E:\laragon\www\posstisla\vendor\yiisoft\yii2\base\Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 E:\laragon\www\posstisla\vendor\yiisoft\yii2\console\Controller.php(182): yii\base\Controller->runAction('', Array)
#11 E:\laragon\www\posstisla\vendor\yiisoft\yii2\base\Module.php(552): yii\console\Controller->runAction('', Array)
#12 E:\laragon\www\posstisla\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate', Array)
#13 E:\laragon\www\posstisla\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate', Array)
#14 E:\laragon\www\posstisla\vendor\yiisoft\yii2\base\Application.php(384): yii\console\Application->handleRequest(Object(yii\console\Request))
#15 E:\laragon\www\posstisla\yii(19): yii\base\Application->run()
#16 {main}
*** failed to apply m210509_014148_vWstok (time: 0.053s)

25 from 27 migrations were applied.

Migration failed. The rest of the migrations are canceled.v

ada error untuk terakhir ketika yii migrate..jd ada table yg gak dibuata atau di alter kak..blh minta databasenya kak/?

**Comment by piantgrunger** [comment]
hapus aja migration 2 terakhir cb jalankan itu cm perbaikan laporan stok
